name: Deploy
run-name: "Deploying ${{ github.event.inputs.application }} to env ${{ github.event.inputs.environment }} from ${{ github.ref_name }}"
on:
  workflow_dispatch:
    inputs:
      application:
        description: 'Choose applicaion'
        default: 'staging'
        required: true
        type: choice
        options:
        - backend
        - admin
      environment:
        description: 'Deploy to env'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - prod

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: '0'

      - name: prepare package
        run: |
          sudo apt install zip -y
          sudo zip -r fs_${{ inputs.application }}_${{ inputs.environment }}.zip *
          echo "#########################################################"
          ls

      # - name: upload s3
      #   run: |
      #     aws s3 cp fs_backend.zip s3://codedeploy-fs-backend/fs_backend.zip

      # - name: create codedeploy deployment
      #   run: |
      #     aws deploy create-deployment \
      #     --application-name fs-backend \
      #     --deployment-config-name CodeDeployDefault.OneAtATime \
      #     --deployment-group-name fs-backend-group \
      #     --description "Deployment" \
      #     --s3-location bucket=codedeploy-fs-backend,bundleType=zip,key=fs_backend.zip
