name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Install SSH Client
      #   run: sudo apt-get install -y openssh-client

      # - name: SFTP Deploy
      #   run: |
      #     if ${{ github.event.pull_request.base.ref == 'main' }}; then
      #       echo "Test"
      #     elif ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}; then
      #       echo "Live"
      #     fi
      - name: Deployment Status
        env:
          DEPLOYMENT_STATUS: Failed
        run: |
            echo "$DEPLOYMENT_STATUS"
            if $DEPLOYMENT_STATUS == "Failed"
            then
              exit 1
            fi
