name: Deploy to AWS Beanstalk
# run-name: "Deploy to ${{ github.event.inputs.environment }} from ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}"
#run-name: &default_name Default Run Name
run-name:
  if: github.event_name == 'pull_request':
  value: Deploy
  else: AAA


on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Choose Env to deploy
        default: 'Staging'
        options:
        - Staging
        - Prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Install SSH Client
      #   run: sudo apt-get install -y openssh-client

      - name: SFTP Deploy
        run: |
          if ${{ github.event.pull_request.base.ref == 'main' }}; then
            echo "Test"
          elif ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}; then
            echo "Live"
          fi
